server:
  port: 8088

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://User-Service
          predicates:
            - Path=/skillverse/users/**
          filters:
            - StripPrefix=1

        - id: admin-service
          uri: lb://User-Service
          predicates:
            - Path=/skillverse/admins/**
          filters:
            - StripPrefix=1

        - id: super-service
          uri: lb://User-Service
          predicates:
            - Path=/skillverse/superadmin/**
          filters:
            - StripPrefix=1

        - id: course-service
          uri: lb://Course-Service
          predicates:
            - Path=/skillverse/courses/**
          filters:
            - StripPrefix=1

        - id: rating-service
          uri: lb://Rating-Service
          predicates:
            - Path=/skillverse/ratings/**
          filters:
            - StripPrefix=1

        - id: enrollment-service
          uri: lb://Enrollment-Service
          predicates:
            - Path=/skillverse/enrollments/**
          filters:
            - StripPrefix=1

        - id: user-auth
          uri: lb://User-Service
          predicates:
            - Path=/skillverse/auth/**
          filters:
            - StripPrefix=1

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
  config:
    import: optional:configserver:http://localhost:8085
  security:
    user:
      name: a
      password: aa



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
    
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
