# Server port
server:
  port: 8081

# Spring applicaton configuration
spring:
  application:
    name: User-Service

# Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/skillverse
    password: Sql#1541
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect

# Config file configuration
  config:
    import: optional:configserver:http://localhost:8085

# Cloud discovery Client configuration & Spring Security OAuth2 Resource Server Configuration
  cloud:
    discovery:
      enabled: true
#  security:
#    user:
#      name: a
#      password: aa
#   oauth2:
#     resourceserver:
#       jwt:
#         issuer-uri: http://localhost:8087

#  jackson:
#    serialization:
#			fail-on-empty-beans: false

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"


# jwt Configuration


# WebClient Configuration
#webclient:
#  hotel-service:
#    base-url: http://HOTEL-SERVICE
#  rating-service:
#    base-url: http://RATING-SERVICE

# Temporary Spring


# Documentation Configguration
springdoc:
  swagger-ui:
    path : /ui-index.html
    operationsSorter : method