# spring Configuration
spring:
  application:
    name: Config-Server
  port: 8085

# spring cloud Configuration 
  cloud:
    config:
      server:
        git:
          uri: 
        clone-on-start: true
        search-paths: ConfigProfiles