# Server Port Configuration
server:
  port: 8085
# spring Configuration
spring:
  application:
    name: Config-Server
# spring cloud Configuration 
  cloud:
    config:
      server:
        git:
          uri: 
        clone-on-start: true
        search-paths: ConfigProfiles
# Cloud discovery Client configuration & Spring Security OAuth2 Resource Server Configuration
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

# Documentation Configguration
springdoc:
  swagger-ui:
    path : /ui-index.html
    operationsSorter : method